apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: okonomimodell-api
  namespace: team-oebs
  labels:
    app: okonomimodell-api
    team: team-oebs

spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 3

  liveness:
    path: /actuator/health/liveness
    initialDelay: 30
    periodSeconds: 5
    failureThreshold: 3

  readiness:
    path: /actuator/health/readiness
    initialDelay: 30
    periodSeconds: 5
    failureThreshold: 3

  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      memory: 2048Mi

  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no

  accessPolicy:
    inbound:
      rules: []
    outbound:
      rules: []
  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-konteringsinfo.nav.no"
    - "https://oebs-konteringsinfo.intern.nav.no"